import {FETCH_DOG_SUCCESS,FETCH_DOG_FAILURE,fetchDog,deleteDog,ADOPT_DOG_FAILURE} from './dog'
import {FETCH_CAT_SUCCESS,FETCH_CAT_FAILURE,fetchCat,deleteCat,ADOPT_CAT_FAILURE} from './cat'

export default {FETCH_CAT_SUCCESS,FETCH_CAT_FAILURE,
    fetchCat,deleteCat,ADOPT_CAT_FAILURE,FETCH_DOG_SUCCESS,FETCH_DOG_FAILURE,fetchDog,deleteDog,ADOPT_DOG_FAILURE}